<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => '510de6eca6248d77d31b339d62437cc995e2fb41',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '5.0.2',
            'version' => '5.0.2.0',
            'reference' => 'da5bdb82c8755f54de112b271b402aaa8df53269',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '8f93648fac8e6bacac8e00a8d325eba4950295e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => '6faf451159fb8ba4126b925ed2d78acfce0dc016',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '5.0.9',
            'version' => '5.0.9.0',
            'reference' => '3dcdfab4c9122874f3915d8bf80a43b9df11852d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mike42/escpos-php' => array(
            'pretty_version' => 'v2.2',
            'version' => '2.2.0.0',
            'reference' => 'e5496cf819b048b11877117bd14a9cea4fb17c03',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mike42/escpos-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpqrcode/phpqrcode' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpqrcode/phpqrcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
